/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../rtl/gcounter.v:1" *)
module gcounter(clk, reset, q);
  (* src = "../rtl/gcounter.v:9" *)
  wire [31:0] _000_;
  (* src = "../rtl/gcounter.v:9" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  (* src = "../rtl/gcounter.v:2" *)
  input clk;
  (* src = "../rtl/gcounter.v:3" *)
  output [31:0] q;
  (* src = "../rtl/gcounter.v:2" *)
  input reset;
  (* src = "../rtl/gcounter.v:7" *)
  wire t;
  sky130_fd_sc_hd__xnor2_1 _115_ (
    .A(q[0]),
    .B(t),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(reset),
    .B(_092_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _117_ (
    .A(q[0]),
    .SLEEP(t),
    .X(_093_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(q[1]),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(reset),
    .B(_094_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(q[0]),
    .B(t),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(q[1]),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xor2_1 _122_ (
    .A(q[2]),
    .B(_096_),
    .X(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _123_ (
    .A(reset),
    .B(_097_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nand3b_1 _124_ (
    .A_N(q[1]),
    .B(q[2]),
    .C(_095_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xor2_1 _125_ (
    .A(q[3]),
    .B(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _126_ (
    .A(reset),
    .B(_099_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nor4_4 _127_ (
    .A(q[0]),
    .B(t),
    .C(q[1]),
    .D(q[2]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(q[3]),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__xor2_1 _129_ (
    .A(q[4]),
    .B(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _130_ (
    .A(reset),
    .B(_102_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__nand3b_1 _131_ (
    .A_N(q[3]),
    .B(q[4]),
    .C(_100_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xor2_1 _132_ (
    .A(q[5]),
    .B(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _133_ (
    .A(reset),
    .B(_104_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__nor2_1 _134_ (
    .A(q[3]),
    .B(q[4]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand3_1 _135_ (
    .A(q[5]),
    .B(_100_),
    .C(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xor2_1 _136_ (
    .A(q[6]),
    .B(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(reset),
    .B(_107_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__nand4b_1 _138_ (
    .A_N(q[5]),
    .B(q[6]),
    .C(_100_),
    .D(_105_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__xor2_1 _139_ (
    .A(q[7]),
    .B(_108_),
    .X(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _140_ (
    .A(reset),
    .B(_109_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__nor4_4 _141_ (
    .A(q[3]),
    .B(q[4]),
    .C(q[5]),
    .D(q[6]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand3_1 _142_ (
    .A(q[7]),
    .B(_100_),
    .C(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xor2_1 _143_ (
    .A(q[8]),
    .B(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(reset),
    .B(_112_),
    .Y(_000_[8])
  );
  sky130_fd_sc_hd__nand4b_1 _145_ (
    .A_N(q[7]),
    .B(q[8]),
    .C(_100_),
    .D(_110_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _146_ (
    .A(q[9]),
    .B(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(reset),
    .B(_114_),
    .Y(_000_[9])
  );
  sky130_fd_sc_hd__nor2_1 _148_ (
    .A(q[7]),
    .B(q[8]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand4_1 _149_ (
    .A(q[9]),
    .B(_100_),
    .C(_110_),
    .D(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _150_ (
    .A(q[10]),
    .B(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _151_ (
    .A(reset),
    .B(_004_),
    .Y(_000_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _152_ (
    .A(q[10]),
    .SLEEP(q[9]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand4_1 _153_ (
    .A(_100_),
    .B(_110_),
    .C(_002_),
    .D(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _154_ (
    .A(q[11]),
    .B(_006_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(reset),
    .B(_007_),
    .Y(_000_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _156_ (
    .A(q[12]),
    .SLEEP(reset),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _157_ (
    .A(q[12]),
    .B(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand3_2 _158_ (
    .A(_100_),
    .B(_110_),
    .C(_002_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor4b_1 _159_ (
    .A(q[9]),
    .B(_010_),
    .C(q[10]),
    .D_N(q[11]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__mux2_2 _160_ (
    .A0(_008_),
    .A1(_009_),
    .S(_011_),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _161_ (
    .A(q[13]),
    .SLEEP(reset),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(q[13]),
    .B(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__buf_2 _163_ (
    .A(_010_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2b_1 _164_ (
    .A_N(q[11]),
    .B(q[12]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor4_1 _165_ (
    .A(q[9]),
    .B(q[10]),
    .C(_014_),
    .D(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__mux2_2 _166_ (
    .A0(_012_),
    .A1(_013_),
    .S(_016_),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _167_ (
    .A(q[14]),
    .SLEEP(reset),
    .X(_017_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(q[14]),
    .B(reset),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _169_ (
    .A(q[11]),
    .B(q[12]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(q[13]),
    .B(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor4_1 _171_ (
    .A(q[9]),
    .B(q[10]),
    .C(_014_),
    .D(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__mux2_2 _172_ (
    .A0(_017_),
    .A1(_018_),
    .S(_021_),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _173_ (
    .A(q[15]),
    .SLEEP(reset),
    .X(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(q[15]),
    .B(reset),
    .Y(_023_)
  );
  sky130_fd_sc_hd__buf_2 _175_ (
    .A(_010_),
    .X(_024_)
  );
  sky130_fd_sc_hd__nor3_1 _176_ (
    .A(q[11]),
    .B(q[12]),
    .C(q[13]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(q[14]),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor4_1 _178_ (
    .A(q[9]),
    .B(q[10]),
    .C(_024_),
    .D(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__mux2_2 _179_ (
    .A0(_022_),
    .A1(_023_),
    .S(_027_),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__clkbuf_1 _180_ (
    .A(_014_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _181_ (
    .A(q[9]),
    .B(q[10]),
    .C(q[14]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _182_ (
    .A(q[15]),
    .B(_025_),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _183_ (
    .A1(_028_),
    .A2(_030_),
    .B1(q[16]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__or3_1 _184_ (
    .A(q[16]),
    .B(_014_),
    .C(_030_),
    .X(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _185_ (
    .A1(_031_),
    .A2(_032_),
    .B1(reset),
    .Y(_000_[16])
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(_025_),
    .B(_029_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2b_1 _187_ (
    .A_N(q[15]),
    .B(q[16]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o31ai_1 _188_ (
    .A1(_028_),
    .A2(_033_),
    .A3(_034_),
    .B1(q[17]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or4_1 _189_ (
    .A(q[17]),
    .B(_024_),
    .C(_033_),
    .D(_034_),
    .X(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _190_ (
    .A1(_035_),
    .A2(_036_),
    .B1(reset),
    .Y(_000_[17])
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(q[15]),
    .B(q[16]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand4_1 _192_ (
    .A(q[17]),
    .B(_025_),
    .C(_029_),
    .D(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _193_ (
    .A1(_028_),
    .A2(_038_),
    .B1(q[18]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__or3_1 _194_ (
    .A(q[18]),
    .B(_014_),
    .C(_038_),
    .X(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _195_ (
    .A1(_039_),
    .A2(_040_),
    .B1(reset),
    .Y(_000_[18])
  );
  sky130_fd_sc_hd__inv_1 _196_ (
    .A(q[18]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand4b_1 _197_ (
    .A_N(q[17]),
    .B(_025_),
    .C(_029_),
    .D(_037_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o31ai_1 _198_ (
    .A1(_041_),
    .A2(_028_),
    .A3(_042_),
    .B1(q[19]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or4_1 _199_ (
    .A(_041_),
    .B(q[19]),
    .C(_024_),
    .D(_042_),
    .X(_044_)
  );
  sky130_fd_sc_hd__a21oi_1 _200_ (
    .A1(_043_),
    .A2(_044_),
    .B1(reset),
    .Y(_000_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _201_ (
    .A(q[20]),
    .SLEEP(reset),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(q[20]),
    .B(reset),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_1 _203_ (
    .A(q[19]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor4_1 _204_ (
    .A(q[18]),
    .B(_047_),
    .C(_024_),
    .D(_042_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__mux2_2 _205_ (
    .A0(_045_),
    .A1(_046_),
    .S(_048_),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__nor2_1 _206_ (
    .A(q[18]),
    .B(q[19]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(q[20]),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o31ai_1 _208_ (
    .A1(_028_),
    .A2(_042_),
    .A3(_050_),
    .B1(q[21]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__or4_1 _209_ (
    .A(q[21]),
    .B(_024_),
    .C(_042_),
    .D(_050_),
    .X(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _210_ (
    .A1(_051_),
    .A2(_052_),
    .B1(reset),
    .Y(_000_[21])
  );
  sky130_fd_sc_hd__nand3b_1 _211_ (
    .A_N(q[20]),
    .B(q[21]),
    .C(_049_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o31ai_1 _212_ (
    .A1(_028_),
    .A2(_042_),
    .A3(_053_),
    .B1(q[22]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or4_1 _213_ (
    .A(q[22]),
    .B(_024_),
    .C(_042_),
    .D(_053_),
    .X(_055_)
  );
  sky130_fd_sc_hd__a21oi_1 _214_ (
    .A1(_054_),
    .A2(_055_),
    .B1(reset),
    .Y(_000_[22])
  );
  sky130_fd_sc_hd__nor4_1 _215_ (
    .A(q[18]),
    .B(q[19]),
    .C(q[20]),
    .D(q[21]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(q[22]),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o31ai_1 _217_ (
    .A1(_028_),
    .A2(_042_),
    .A3(_057_),
    .B1(q[23]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__or4_1 _218_ (
    .A(q[23]),
    .B(_024_),
    .C(_042_),
    .D(_057_),
    .X(_059_)
  );
  sky130_fd_sc_hd__a21oi_1 _219_ (
    .A1(_058_),
    .A2(_059_),
    .B1(reset),
    .Y(_000_[23])
  );
  sky130_fd_sc_hd__inv_1 _220_ (
    .A(q[23]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor4_1 _221_ (
    .A(q[15]),
    .B(q[16]),
    .C(q[17]),
    .D(q[22]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand4_1 _222_ (
    .A(_025_),
    .B(_029_),
    .C(_056_),
    .D(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkbuf_1 _223_ (
    .A(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__o31ai_1 _224_ (
    .A1(_060_),
    .A2(_028_),
    .A3(_063_),
    .B1(q[24]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__or4_1 _225_ (
    .A(_060_),
    .B(q[24]),
    .C(_024_),
    .D(_063_),
    .X(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _226_ (
    .A1(_064_),
    .A2(_065_),
    .B1(reset),
    .Y(_000_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _227_ (
    .A(q[25]),
    .SLEEP(reset),
    .X(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _228_ (
    .A(q[25]),
    .B(reset),
    .Y(_067_)
  );
  sky130_fd_sc_hd__inv_1 _229_ (
    .A(q[24]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor4_1 _230_ (
    .A(q[23]),
    .B(_068_),
    .C(_024_),
    .D(_063_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__mux2_2 _231_ (
    .A0(_066_),
    .A1(_067_),
    .S(_069_),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(q[23]),
    .B(q[24]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(q[25]),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o31ai_1 _234_ (
    .A1(_028_),
    .A2(_063_),
    .A3(_071_),
    .B1(q[26]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__or4_1 _235_ (
    .A(q[26]),
    .B(_024_),
    .C(_062_),
    .D(_071_),
    .X(_073_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(_072_),
    .A2(_073_),
    .B1(reset),
    .Y(_000_[26])
  );
  sky130_fd_sc_hd__nand3b_1 _237_ (
    .A_N(q[25]),
    .B(q[26]),
    .C(_070_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o31ai_1 _238_ (
    .A1(_028_),
    .A2(_063_),
    .A3(_074_),
    .B1(q[27]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__or4_1 _239_ (
    .A(q[27]),
    .B(_010_),
    .C(_062_),
    .D(_074_),
    .X(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _240_ (
    .A1(_075_),
    .A2(_076_),
    .B1(reset),
    .Y(_000_[27])
  );
  sky130_fd_sc_hd__nor4_1 _241_ (
    .A(q[23]),
    .B(q[24]),
    .C(q[25]),
    .D(q[26]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(q[27]),
    .B(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o31ai_1 _243_ (
    .A1(_014_),
    .A2(_063_),
    .A3(_078_),
    .B1(q[28]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__or4_1 _244_ (
    .A(q[28]),
    .B(_010_),
    .C(_062_),
    .D(_078_),
    .X(_080_)
  );
  sky130_fd_sc_hd__a21oi_1 _245_ (
    .A1(_079_),
    .A2(_080_),
    .B1(reset),
    .Y(_000_[28])
  );
  sky130_fd_sc_hd__nand3b_1 _246_ (
    .A_N(q[27]),
    .B(q[28]),
    .C(_077_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o31a_1 _247_ (
    .A1(_014_),
    .A2(_063_),
    .A3(_081_),
    .B1(q[29]),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor4_1 _248_ (
    .A(q[29]),
    .B(_014_),
    .C(_063_),
    .D(_081_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21ba_2 _249_ (
    .A1(_082_),
    .A2(_083_),
    .B1_N(reset),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__inv_1 _250_ (
    .A(q[28]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand4b_1 _251_ (
    .A_N(q[27]),
    .B(_084_),
    .C(q[29]),
    .D(_077_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o31ai_1 _252_ (
    .A1(_014_),
    .A2(_063_),
    .A3(_085_),
    .B1(q[30]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__or4_1 _253_ (
    .A(q[30]),
    .B(_010_),
    .C(_062_),
    .D(_085_),
    .X(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_086_),
    .A2(_087_),
    .B1(reset),
    .Y(_000_[30])
  );
  sky130_fd_sc_hd__nor4b_1 _255_ (
    .A(q[27]),
    .B(q[28]),
    .C(q[29]),
    .D_N(q[30]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_077_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o31ai_1 _257_ (
    .A1(_014_),
    .A2(_063_),
    .A3(_089_),
    .B1(q[31]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__or4_1 _258_ (
    .A(q[31]),
    .B(_010_),
    .C(_062_),
    .D(_089_),
    .X(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _259_ (
    .A1(_090_),
    .A2(_091_),
    .B1(reset),
    .Y(_000_[31])
  );
  sky130_fd_sc_hd__nand2b_1 _260_ (
    .A_N(reset),
    .B(t),
    .Y(_001_)
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _261_ (
    .CLK(clk),
    .D(_001_),
    .Q(t)
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _262_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(q[0])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _263_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(q[1])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _264_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(q[2])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _265_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(q[3])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _266_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(q[4])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _267_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(q[5])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _268_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(q[6])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _269_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(q[7])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _270_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(q[8])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _271_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(q[9])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _272_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(q[10])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _273_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(q[11])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _274_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(q[12])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _275_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(q[13])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _276_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(q[14])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _277_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(q[15])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _278_ (
    .CLK(clk),
    .D(_000_[16]),
    .Q(q[16])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _279_ (
    .CLK(clk),
    .D(_000_[17]),
    .Q(q[17])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _280_ (
    .CLK(clk),
    .D(_000_[18]),
    .Q(q[18])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _281_ (
    .CLK(clk),
    .D(_000_[19]),
    .Q(q[19])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _282_ (
    .CLK(clk),
    .D(_000_[20]),
    .Q(q[20])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _283_ (
    .CLK(clk),
    .D(_000_[21]),
    .Q(q[21])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _284_ (
    .CLK(clk),
    .D(_000_[22]),
    .Q(q[22])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _285_ (
    .CLK(clk),
    .D(_000_[23]),
    .Q(q[23])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _286_ (
    .CLK(clk),
    .D(_000_[24]),
    .Q(q[24])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _287_ (
    .CLK(clk),
    .D(_000_[25]),
    .Q(q[25])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _288_ (
    .CLK(clk),
    .D(_000_[26]),
    .Q(q[26])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _289_ (
    .CLK(clk),
    .D(_000_[27]),
    .Q(q[27])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _290_ (
    .CLK(clk),
    .D(_000_[28]),
    .Q(q[28])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _291_ (
    .CLK(clk),
    .D(_000_[29]),
    .Q(q[29])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _292_ (
    .CLK(clk),
    .D(_000_[30]),
    .Q(q[30])
  );
  (* src = "../rtl/gcounter.v:9" *)
  sky130_fd_sc_hd__dfxtp_1 _293_ (
    .CLK(clk),
    .D(_000_[31]),
    .Q(q[31])
  );
endmodule
